name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
    commits:
      - '^feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
    commits:
      - '^fix'
  - title: '📝 Documentation'
    labels:
      - 'documentation'
    commits:
      - '^docs'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
    commits:
      - '^chore'
  - title: '♻️ Refactoring'
    labels:
      - 'refactor'
    commits:
      - '^refactor'
  - title: '🎨 Style'
    labels:
      - 'style'
    commits:
      - '^style'
  - title: '🧪 Testing'
    labels:
      - 'test'
    commits:
      - '^test'
change-template: '- $TITLE @$AUTHOR ($URL)'
version-resolver:
  default: patch
template: |
  ## What's Changed

  $CHANGES

  ## 👥 Contributors

  $CONTRIBUTORS
