name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    commits:
      - '^feat'
  - title: '🐛 Bug Fixes'
    commits:
      - '^fix'
  - title: '📝 Documentation'
    commits:
      - '^docs'
  - title: '🧰 Maintenance'
    commits:
      - '^chore'
  - title: '♻️ Refactoring'
    commits:
      - '^refactor'
  - title: '🎨 Style'
    commits:
      - '^style'
  - title: '🧪 Testing'
    commits:
      - '^test'
change-template: '- $TITLE @$AUTHOR ($COMMIT)'
version-resolver:
  default: patch
template: |
  ## What's Changed

  $CHANGES

  ## 👥 Contributors

  $CONTRIBUTORS
