name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
        pip install flake8 pytest-cov
    - name: Run linter
      run: flake8 . --config=.flake8
    - name: Run tests with coverage
      run: pytest --cov=src --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results
        path: pytest-results
      if: ${{ always() }}

  todo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "TODO to Issue"
      uses: "alstr/todo-to-issue-action@v4.13"
